# Generated by Django 5.0.3 on 2024-03-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_created_task_date_task_datecompleted_task_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
    ]
